#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx
echo "server {
    listen 80;
    server_name localhost;

    location / {
        echo 'Hello World!' > /usr/share/nginx/html/index.html;
        return 200;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx without systemctl
service nginx restart
