#!/usr/bin/env bash
#script to run whoami command under the user passed as an argument
#usage: ./0-iamsomeoneelse <username>
# Create a new user
sudo adduser $1

# Run the whoami command under the new user
sudo -u $1 whoami
